// GENERATED by scripts/palette/derive_ramp.mjs — do not edit by hand.
//
// 7 classes resampled from the 12-hex source ramp at equal arc length in CIELAB.
// Re-derive with:  node scripts/palette/derive_ramp.mjs --write
//
// Adjacent dE76 steps: 30.95 29.79 34.84 32.05 32.22 30.25
//   coefficient of variation 0.2364 (12-hex source) -> 0.0524 (this ramp)
// Minimum adjacent dE76 under simulated CVD (Machado 2009, severity 1.0):
//   protanopia 19.34 · deuteranopia 12.68 · tritanopia 12.04
//   (the source ramp: 9.01 · 8.43 · 7.93)
// L* runs 96.9 -> 12.9, monotone decreasing, so it
// survives grayscale printing as well as all three CVD types.

export const CHOROPLETH_COLORS = [
  "#FFF9B0",
  "#FFCC5F",
  "#FE9956",
  "#EB5D5E",
  "#CB3977",
  "#8C2C85",
  "#2E0B59",
] as const;

/** Number of classes the pipeline computes breaks for. len(breaks) === CLASSES - 1. */
export const CLASSES = 7;

/**
 * A ZCTA that is DRAWN but reported by neither source. It is not transparent:
 * transparent made "no data" visually identical to "not a ZCTA at all" and to a
 * genuine zero. It gets its own legend entry.
 */
export const NO_DATA_COLOR = "#E8E8E8";

/** For signed series. Painting signed data on a sequential ramp is a correctness bug. */
export const DIVERGING_COLORS = [
  "#2166AC",
  "#67A9CF",
  "#D1E5F0",
  "#F7F7F7",
  "#FDDBC7",
  "#EF8A62",
  "#B2182B",
] as const;

/** Fixed, symmetric, clamped. The end swatch reads ">= +20%", which is true in every regime. */
export const DIVERGING_BOUND_PCT = 20;
