// GENERATED by scripts/palette/derive_ramp.mjs — do not edit by hand.
//
// 14 classes resampled from the 12-hex source ramp at equal arc length in CIELAB.
// Re-derive with:  node scripts/palette/derive_ramp.mjs --write
//
// Adjacent dE76 steps: 15.8 15.45 14.33 15.97 15.32 15.95 15.63 15.81 15.69 15.11 15.39 13.79 15.66
//   coefficient of variation 0.2364 (12-hex source) -> 0.0402 (this ramp)
//   smallest adjacent step to a normal-vision reader 13.79, far above
//   the ~2.3 just-noticeable difference, so all 14 are separable to most readers.
//
// THE ACCESSIBILITY GUARANTEE, which is the number that governs the class count.
// Under simulated colour-vision deficiency (Machado 2009, severity 1.0) ADJACENT
// classes are not separable at this count — protanopia 8.32 ·
// deuteranopia 7.62 · tritanopia 7.79 dE76, against a 10 dE76 floor.
// Classes 2 apart are. So two ZIPs differing by 14.3% of the range look
// different to EVERY reader, which is exactly what the 7-class ramp guaranteed at
// 14.3%. A colour-blind reader resolves 7 bands here and resolved 7
// before; normal vision resolves 14 instead of 7. The ramp's CVD arc length is
// a fixed budget — about 84 dE76, bounded by the usable L* range — so a higher
// class count can only spend it thinner, and 15 already fails this check.
//
// L* runs 96.9 -> 12.9, monotone decreasing, so it
// survives grayscale printing as well as all three CVD types.

export const CHOROPLETH_COLORS = [
  "#FFF9B0",
  "#FFEC87",
  "#FFD065",
  "#FFB64B",
  "#FFA054",
  "#F68657",
  "#EE6B5B",
  "#E94F60",
  "#D43D6A",
  "#C7377D",
  "#A72D80",
  "#882D88",
  "#5E2079",
  "#2E0B59",
] as const;

/** Number of classes the pipeline computes breaks for. len(breaks) === CLASSES - 1. */
export const CLASSES = 14;

/**
 * A ZCTA that is DRAWN but reported by neither source. It is not transparent:
 * transparent made "no data" visually identical to "not a ZCTA at all" and to a
 * genuine zero. It gets its own legend entry.
 */
export const NO_DATA_COLOR = "#E8E8E8";
