#!/usr/bin/env node
// Regenerates tree.txt — the source-file map linked from the README.
//
// Lists only files Git tracks, so build output, node_modules, caches and
// anything else ignored never appear. Run via `npm run tree`; the pre-commit
// hook in .githooks/ runs it automatically.

import { execFileSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";

// Directories that add length without adding information: generated shadcn
// primitives and the monthly data archive. Summarised as a single count line.
const COLLAPSE = ["src/components/ui", "public/data/archive"];

const tracked = execFileSync("git", ["ls-files"], { encoding: "utf8" })
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean);

const collapsedCounts = new Map();
const paths = [];

for (const file of tracked) {
  const bucket = COLLAPSE.find((dir) => file.startsWith(dir + "/"));
  if (bucket) {
    collapsedCounts.set(bucket, (collapsedCounts.get(bucket) ?? 0) + 1);
    continue;
  }
  paths.push(file);
}

// Build a nested tree from the flat path list.
const root = new Map();
for (const p of paths) {
  const parts = p.split("/");
  let node = root;
  parts.forEach((part, i) => {
    const isFile = i === parts.length - 1;
    if (!node.has(part)) node.set(part, isFile ? null : new Map());
    if (!isFile) node = node.get(part);
  });
}
for (const [dir, count] of collapsedCounts) {
  const parts = dir.split("/");
  let node = root;
  parts.forEach((part, i) => {
    const isLast = i === parts.length - 1;
    if (isLast) node.set(part, new Map([[`… ${count} file${count === 1 ? "" : "s"}`, null]]));
    else {
      if (!node.has(part)) node.set(part, new Map());
      node = node.get(part);
    }
  });
}

const lines = [];
function render(node, prefix) {
  // Directories first, then files; alphabetical within each group.
  const entries = [...node.entries()].sort((a, b) => {
    const aDir = a[1] !== null, bDir = b[1] !== null;
    if (aDir !== bDir) return aDir ? -1 : 1;
    return a[0].localeCompare(b[0]);
  });
  entries.forEach(([name, child], i) => {
    const last = i === entries.length - 1;
    lines.push(`${prefix}${last ? "└── " : "├── "}${name}${child !== null ? "/" : ""}`);
    if (child !== null) render(child, `${prefix}${last ? "    " : "│   "}`);
  });
}
render(root, "");

const output = `Domapus — tracked source files
Generated by scripts/generate-tree.mjs (npm run tree). Do not edit by hand.

.
${lines.join("\n")}
`;

// Only rewrite when the content actually differs, so the pre-commit hook does
// not create an empty change on every commit.
let existing = "";
try { existing = readFileSync("tree.txt", "utf8"); } catch { /* first run */ }
if (existing !== output) {
  writeFileSync("tree.txt", output);
  console.log(`tree.txt updated (${lines.length} entries)`);
} else {
  console.log("tree.txt already up to date");
}
